config/routes.rb
SalesLeadx::Engine.routes.draw do
  
  resources :sales_leads, :only => [:index, :new, :create]
  resources :sales_leads do
    collection do
      get :search
      get :search_results      
      get :stats
      get :stats_results
    end          
  end  
  
  root :to => 'sales_leads#index'
end

app/models/sales_leadx/sales_lead.rb
module SalesLeadx
  class SalesLead < ActiveRecord::Base
    attr_accessor :customer_name, :lead_source_name, :sale_success_value, :close_lead_value, :lead_status_name
    
    attr_accessible :lead_eval, :contact_instruction, :customer_id, :last_updated_by_id, :lead_accuracy_scale, :lead_quality_scale, 
                    :lead_info, :sale_success, :lead_source_id, :lead_status_id, :provider_id, :subject, :lead_date, :provider_name_autocomplete,
                    :customer_name_autocomplete, :initial_order_total, :close_lead_by_id,
                    :customer_name, :lead_source_name, :sale_success_value, :close_lead_value,
                    :as => :role_new
    attr_accessible :lead_eval, :contact_instruction, :last_updated_by_id, :lead_accuracy_scale, :lead_quality_scale, :close_lead, :lead_date,
                    :close_lead_date, :close_lead_by_id, :lead_info, :sale_success, :lead_source_id, :provider_id, :subject, :lead_status_id,
                    :provider_name_autocomplete, :customer_name_autocomplete, :customer_name, :initial_order_total, :close_lead_by_id, 
                    :customer_name, :lead_source_name, :sale_success_value, :close_lead_value, :lead_status_name,
                    :as => :role_update 
                    
    attr_accessor :customer_id_s, :start_date_s, :end_date_s, :zone_id_s, :sales_id_s, :lead_source_id_s, :lead_status_s
    attr_accessible :customer_id_s, :start_date_s, :end_date_s,:zone_id_s, :sales_id_s, :lead_source_id_s, :lead_status_s,
                    :as => :role_search_stats                
                    
    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    belongs_to :provider, :class_name => 'Authentify::User'
    belongs_to :close_lead_by, :class_name => 'Authentify::User'
    has_many :logs, :class_name => "Commonx::Log"
    belongs_to :customer, :class_name => SalesLeadx.customer_class.to_s
    belongs_to :lead_source, :class_name => 'Commonx::MiscDefinition'
    belongs_to :lead_status, :class_name => 'Commonx::MiscDefinition'
    belongs_to :lead_category, :class_name => 'Commonx::MiscDefinition'
    
    validates :lead_info, :subject, :lead_date, :presence => true
    validates :customer_id, :provider_id, :lead_source_id, :presence => true, :numericality => {:greater_than => 0}
    validates :lead_status_id, :numericality => {:greater_than => 0}, :if => 'lead_status_id.present?'
    validates :lead_category_id, :numericality => {:greater_than => 0}, :if => 'lead_category_id.present?'
    validates :lead_info, :uniqueness => {:scope => :customer_id, :case_sensitive => false, :message => I18n.t('Duplicate Lead Info!')}
    
    def customer_name_autocomplete
      self.customer.try(:name)
    end

    def customer_name_autocomplete=(name)
      self.customer = SalesLeadx.customer_class.find_by_name(name) if name.present?
    end
    
    def provider_name_autocomplete
      self.provider.try(:name)
    end

    def provider_name_autocomplete=(name)
      self.provider = Authentify::User.find_by_name(name) if name.present?
    end
    
  end
end

app/controllers/sales_leadx/application_controller.rb
module SalesLeadx
  class ApplicationController < ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    
    before_filter :require_signin
    before_filter :max_pagination
    before_filter :check_access_right 
    before_filter :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_filter :delete_session_variable, :only => [:create, :update]  #for parent_record_id & parent_resource in check_access_right
    before_filter :view_in_config?
    
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination')
    end
    
    def view_in_config?
      @view_in_config = Authentify::AuthentifyUtility.load_view_in_config
    end
  end
end

app/controllers/sales_leadx/sales_leads_controller.rb
require_dependency "sales_leadx/application_controller"

module SalesLeadx
  class SalesLeadsController < ApplicationController
    before_filter :require_employee
    before_filter :load_customer
    
    helper_method :lead_sources, :lead_status
    
   def index
      @title= "销售线索"
      @sales_leads = params[:sales_leadx_sales_leads][:model_ar_r]
      @sales_leads = @sales_leads.where(:customer_id => @customer.id) if @customer
      @sales_leads = @sales_leads.page(params[:page]).per_page(@max_pagination)
      @erb_code = find_config_const('sales_lead_index_view', 'sales_leadx')
    end
  
    def new
      @title= "新销售线索"
      @sales_lead = SalesLeadx::SalesLead.new()
      @erb_code = find_config_const('sales_lead_new_view', 'sales_leadx')
    end
  
    def create
      @sales_lead = SalesLeadx::SalesLead.new(params[:sales_lead], :as => :role_new)
      @customer = SalesLeadx.customer_class.find_by_id(params[:sales_lead][:customer_id]) if params[:sales_lead].present? && params[:sales_lead][:customer_id].present?
      unless @customer
        cust = SalesLeadx.customer_class.find_by_name(@sales_lead.customer_name_autocomplete) if @sales_lead.customer_name_autocomplete.present?
        @sales_lead.customer_id = cust.id if cust.present?
      end
      #provider id from autocomplete
      provider = Authentify::User.find_by_name(@sales_lead.provider_name_autocomplete) if @sales_lead.provider_name_autocomplete.present?
      @sales_lead.provider_id = provider.id if provider.present?
      @sales_lead.last_updated_by_id = session[:user_id]
      if @sales_lead.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        @erb_code = find_config_const('sales_lead_new_view', 'sales_leadx')
        flash.now[:error] = t('Data Error. Not Saved!')
        render 'new'
      end

    end
  
    def edit
      @title= "更新销售线索"      
      @sales_lead = SalesLeadx::SalesLead.find_by_id(params[:id])
      @erb_code = find_config_const('sales_lead_edit_view', 'sales_leadx')
    end
  
    def update
      @sales_lead = SalesLeadx::SalesLead.find_by_id(params[:id])
      #provider id from autocomplete
      provider = Authentify::User.find_by_name(@sales_lead.provider_name_autocomplete) if @sales_lead.provider_name_autocomplete.present?
      @sales_lead.provider_id = provider.id if provider.present?
      @sales_lead.last_updated_by_id = session[:user_id]
      params[:sales_lead][:initial_order_total] = '' if params[:sales_lead][:sale_success] == 'false'
      if @sales_lead.update_attributes(params[:sales_lead], :as => :role_update)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
      else
        @erb_code = find_config_const('sales_lead_edit_view', 'sales_leadx')
        flash.now[:error] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
  
    def show
      @title= "销售线索内容"
      #nested with customer
      @sales_lead = SalesLeadx::SalesLead.find_by_id(params[:id])
      @erb_code = find_config_const('sales_lead_show_view', 'sales_leadx')
    end
    
    protected
        
    def lead_sources
      Commonx::MiscDefinition.where(:for_which => 'sales_lead_source').where(:active => true).order("ranking_index")
    end
    
    def lead_status
      Commonx::MiscDefinition.where(:for_which => 'sales_lead_status').where(:active => true).order('ranking_index')
    end
    
    def load_customer
      @customer = SalesLeadx.customer_class.find_by_id(params[:customer_id]) if params[:customer_id].present?
      @customer = SalesLeadx.customer_class.find_by_id(SalesLeadx::SalesLead.find_by_id(params[:id]).customer_id) if params[:id].present?
    end
    
  end
end

app/helpers/sales_leadx/application_helper.rb
module SalesLeadx
  module ApplicationHelper
  end
end

app/helpers/sales_leadx/sales_leads_helper.rb
module SalesLeadx
  module SalesLeadsHelper
  end
end

app/views/sales_leadx/sales_leads/_form.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<%= simple_form_for(@sales_lead) do |f| %>    
 
  <%= f.input :lead_date, :label => t("Date"), :as => :string%>
  <%= f.input :customer_name, :label => t('Customer Name'), :readonly => true, :required => false, :input_html => {:value => @customer.name} %>  
  <%= f.input :subject, :label => t('Subject'), :hint => '一句话说明线索是什么', :readonly => readonly?(@sales_lead, 'subject') %>
  <%= f.input :lead_info, :label => t('Lead Info'), :input_html => {:rows => 4}, :readonly => readonly?(@sales_lead, 'lead_info') %>
  <%= f.input :contact_instruction, :label => t('Contact Instruction'), :hint => '联系人及电话等联系方式', :input_html => { :rows => 6}, :readonly => readonly?(@sales_lead, 'contact_instruction') %>
  <% if readonly?(@sales_lead, 'lead_source_id') %>
    <%= f.input :lead_source_name, :label => t('Lead Source'), :input_html => {:value => @sales_lead.lead_source.name}, :readonly => true %>  
  <% else %>
    <%= f.input :lead_source_id, :label => t('Lead Source'), :collection => lead_sources() %> 
  <% end %> 
  <%= f.input :lead_status_id, :label => t('Lead Status'), :collection => lead_status() unless readonly?(@sales_lead, 'lead_status_id') %>    
  <%= f.input :lead_status_name, :label => t('Lead Status'), :input_html => {:value => @sales_lead.lead_status.name} if readonly?(@sales_lead, 'lead_status_id') %>       
  <%= f.input :lead_eval, :label => t('Lead Eval'), :input_html => { :rows => 4}, :readonly => readonly?(@sales_lead, 'lead_eval')  %>
  <% if readonly?(@sales_lead, 'sale_success') %>
    <%= f.input :sale_success_value, :label => t('Sale Success'), :readonly => true, :input_html => {:value => @sales_lead.sale_success ? t('Yes') : t('No') } %>
  <% else %>
    <%= f.input :sale_success, :label => t('Sale Success'), :collection => [[t('Yes'), true], [t('No'), false]], :include_blank => true %>
  <% end %>
  <div id="sales_lead_order_total">
  <%= f.input :initial_order_total, :label => t('Init. Order Amount($)'), :hint => '初次订单金额', :readonly => readonly?(@sales_lead, 'initial_order_total') %> 
  </div>
  <% if readonly?(@sales_lead, 'close_lead') %>
    <%= f.input :close_lead_value, :label => t('Close Lead'), :readonly => true, :input_html => {:value => @sales_lead.close_lead ? t('Yes') : t('No') } %>
  <% else %>
    <%= f.input :close_lead, :label => t('Close Lead'), :collection => [['Yes', true], ['No', false]], :include_blank => true %>
  <% end %>
  <%= f.input :lead_accuracy_scale, :label => t('Accuracy Scale'), :collection => 1..10, :include_blank => true, :readonly => readonly?(@sales_lead, 'lead_accuracy_scale') %>
  <%= f.input :lead_quality_scale, :label => t('Quality Scale'), :collection => 1..10, :include_blank => true, :readonly => readonly?(@sales_lead, 'lead_quality_scale') %>
  <%= f.input :provider_name_autocomplete, :input_html => { data: {autocomplete_source: SUBURI + authentify.autocomplete_users_path}}, :placeholder => "输入关键字", 
              :label => t('Lead Provider'), :required => true  %>        
  
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %> 
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>  

<% end %>

app/views/sales_leadx/sales_leads/_form_new.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<%= simple_form_for(@sales_lead) do |f| %>    
 
  <%= f.input :lead_date, :label => t("Date"), :as => :string%>
  <%= f.input :customer_name, :label => t('Customer Name'), :readonly => true, :required => false, :input_html => {:value => @customer.name} %>
  <%= f.input :customer_id, :as => :hidden, :input_html => {:value => @customer.id} %>  
  <%= f.input :subject, :label => t('Subject'), :placeholder => '一句话说明线索是什么' %>
  <%= f.input :lead_info, :label => t('Lead Info:'), :input_html => {:rows => 4} %>
  <%= f.input :contact_instruction, :label => t('Contact Instruction:'), :hint => '联系人及电话等联系方式', :input_html => { :rows => 6} %>  
  <%= f.input :lead_source_id, :label => t('Lead Source'), :collection => lead_sources(), :include_blank => true %> 
  <%= f.input :lead_status_id, :label => t('Lead Status'), :collection => lead_status(), :include_blank => true %>    
  <%= f.input :lead_eval, :label => t('Lead Eval'), :input_html => { :rows => 4} %> 
  <%= f.input :lead_accuracy_scale, :label => t('Accuracy Scale'), :collection => 1..10, :include_blank => true %>
  <%= f.input :lead_quality_scale, :label => t('Quality Scale'), :collection => 1..10, :include_blank => true %>
  <%= f.input :provider_id, :label => t('Provider'), :collection => Authentify::UsersHelper.return_users('create', params[:controller]),
                                                   :label_method => :name, :value_method => :id  %>        
     
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %> 

<% end %> 

app/views/sales_leadx/sales_leads/_form_new_without_customer.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<%= simple_form_for @sales_lead do |f| %>    
 
  <%= f.input :lead_date, :label => t("Date"), :as => :string%>
  <%= f.input :customer_name_autocomplete, :input_html => { data: {autocomplete_source: SUBURI + eval(SalesLeadx.customer_autocomplete_path)}}, :placeholder => "输入关键字", 
                                           :label => "客户 ：", :required => true %>  
  <%= f.input :subject, :label => t('Subject'), :placeholder => '一句话说明' %>
  <%= f.input :lead_info, :label => t('Lead Info'), :input_html => {:rows => 6} %>
  <%= f.input :contact_instruction, :label => t('Contact Instruction'), :hint => '联系人及电话等联系方式', :input_html => { :rows => 4} %>  
  <%= f.input :lead_source_id, :label => t('Lead Source'), :collection => lead_sources(), :include_blank => true %>     
  <%= f.input :lead_status_id, :label => t('Lead Status'), :collection => lead_status(), :include_blank => true %>    
  <%= f.input :lead_eval, :label => t('Lead Eval:'), :input_html => { :rows => 4} %> 
  <%= f.input :lead_accuracy_scale, :label => t('Accuracy Scale'), :collection => 1..10, :include_blank => true %>
  <%= f.input :lead_quality_scale, :label => t('Quality Scale'), :collection => 1..10, :include_blank => true %>
  <%= f.input :provider_name_autocomplete, :input_html => { data: {autocomplete_source: SUBURI + authentify.autocomplete_users_path}}, :placeholder => "输入关键字", 
                                           :label => t('Lead Provider'), :required => true %>   
  
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>  

<% end %>

app/views/sales_leadx/sales_leads/_index_partial.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>
  <div class="pigination"><%= will_paginate models %></div>
 
  <table class="table table-striped">
  <tr>
    <th>#</th>
    <th><%=t('Enter Date') %></th>
    <th><%=t('Customer Short Name') %></th>
    <th><%=t('Subject') %></th>
    <th><%=t('Lead Detail') %></th>
    <th><%=t('Lead Quality Scale') %></th>
    <th><%=t('Make Sale') %></th>
    <th><%=t('Lead Status') %></th>
    <th><%=t('Init. Order Amount($)') %></th>
    <th><%=t('Lead Provider') %></th>
    <th></th>
 
  </tr>

<% models.each do |r| %>
  <tr>
  	<% if has_action_right?('show', 'sales_leadx_sales_leads', r) %>
  	  <td><%= link_to r.id.to_s, SUBURI + "/authentify/view_handler?index=1&url=#{sales_lead_path(r)}" %></td>
  	<% else %>
  	  <td><%= r.id %></td>
  	<% end %>
  	<td><%= r.lead_date.strftime("%Y/%m/%d") %></td>
    <td><%= prt(r, 'customer.short_name') %></td>   
    <td><%= prt(r, :subject) %></td>
    <td><%= prt(r, :lead_info)[0..40] %></td>
    <td><%= prt(r, :lead_quality_scale) %></td>
    <td><%= prt(r, :sale_success) ? t('Yes') : t('No') %></td>
    <td><%= prt(r, 'lead_status.name') %></td>
    <td><%= number_with_delimiter(prt(r, :initial_order_total)) %></td>
    <td><%= prt(r, 'provider.name') %></td>    
    <td><%= link_to t('Edit'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI::escape(edit_sales_lead_path(r, :parent_record_id => r.customer.id, :parent_resource => SalesLeadx.customer_class.to_s.underscore.pluralize))}", :class => BUTTONS_CLS['action'] if has_action_right?('update', params[:controller], r) %></td>

  </tr>
<% end %>
</table>
<table class="table table-striped">
  <tr>
    <th>
    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<%= link_to 'New Sales Leads', SUBURI + "/authentify/view_handler?index=1&url=#{CGI::escape(new_sales_lead_path)}", :class => BUTTONS_CLS['action'] if @customer.blank? && has_action_right?('create', params[:controller]) %>  
              &nbsp;&nbsp;&nbsp;
              <%= link_to 'New Sales Leads', SUBURI + "/authentify/view_handler?index=1&url=#{CGI::escape(new_sales_lead_path(:customer_id => @customer.id, :parent_record_id => @customer, :parent_resource => SalesLeadx.customer_class.to_s.underscore.pluralize))}", :class => BUTTONS_CLS['action'] if @customer.present? && has_action_right?('create', params[:controller]) %>
    </th>
  </tr>
</table>

<% end %>
  

app/views/sales_leadx/sales_leads/create.html.erb
<h4>SalesLeads#create</h4>
<p>Find me in app/views/customerx/sales_leads/create.html.erb</p>

app/views/sales_leadx/sales_leads/edit.html.erb
<div id="main_body">
<h4><%=t('Edit Sales Lead') %></h4>

<%= render 'form' %>

</div>

app/views/sales_leadx/sales_leads/index.html.erb
<div id="main_body">
<h4><%= t('Sales Leads') %></h4>
<%= render partial: 'index_partial', locals: {models: @sales_leads} %>
</div>

app/views/sales_leadx/sales_leads/new.html.erb
<div id="main_body">
<h4><%=t('New Sales Lead') %></h4>
<% if @customer %>
  <%= render 'form_new' %>
<% else %>
  <%= render 'form_new_without_customer' %>
<% end %>

</div>

app/views/sales_leadx/sales_leads/show.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>
<div id="main_body">

<h4><%=t('Sales Lead Info') %></h4>

<p>
  <b><%=t('Customer') %>:</b>
  <%= @customer.name %>
</p>
<p>
  <b><%=t('Zone') %>:</b>
  <%= @customer.zone.zone_name %>
</p>
<p>
  <b><%=t('Subject') %>:</b>
  <%= @sales_lead.subject %>
</p>
<p>
  <b><%=t('Enter Date') %>:</b>
  <%= (@sales_lead.created_at + 8.hours).strftime("%Y/%m/%d") %>
</p>
<p>
  <b><%=t('Lead Provider') %>:</b>
  <%= @sales_lead.provider.name %>
</p>
<p>
  <b><%=t('Lead Info') %></b>
  <%= @sales_lead.lead_info %>
</p>
<p>
  <b><%=t('Contact Instruction') %>:</b>
  <%= @sales_lead.contact_instruction %>
</p>
<p>
  <b><%=t('Lead Quality(1..10)') %>:</b>
  <%= @sales_lead.lead_quality_scale %>
</p>
<p>
  <b><%=t('Lead Accuracy(1..10)') %>:</b>
  <%= @sales_lead.lead_accuracy_scale %>
</p>

<p>
  <b><%=t('Sale Success') %>:</b>
  <%= @sales_lead.sale_success %>
</p>
<% if @sales_lead.sale_success %>
<p>
  <b><%=t('Init. Order Amount($)') %>:</b>
  <%= number_with_delimiter(@sales_lead.initial_order_total) %>
</p>
<% end %>
<p>
  <b><%=t('Lead Status') %>:</b>
  <%= @sales_lead.lead_status.name %>
</p>
<p>
  <b><%=t('Lead Source') %>:</b>
  <%= @sales_lead.lead_source.name %>
</p>
<p>
  <b><%=t('Last Updated By')%>:</b>
  <%= @sales_lead.last_updated_by.name %>
</p>
<p>
  <b><%=t('Lead Logs') %>:</b>
  <ul>
<% Commonx::Log.where('resource_id = ? AND resource_name = ?', @sales_lead.id, params[:controller].sub('/', '_')).order("id DESC").each do |f| %>
  <li>
  <%= (f.created_at + 8.hours).strftime("%Y-%m-%d").to_s + ', ' + f.input_by.name + ', '+ f.log %>
  </li>
<% end %>
</ul>
</p>

<table class="table table-striped">
  <tr>
    <th>
    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    	<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action'] %>
		<%= link_to 'New Log', SUBURI + commonx.new_log_path(:resource_id => @sales_lead.id, :resource_name => params[:controller], :subaction => 'sales_lead', :format => :js), 
                              :remote => true, :id => 'new_log_link', :class => BUTTONS_CLS['action'] if has_action_right?('create_sales_lead', 'commonx_logs') %>    </th>
  </tr>
</table>
  
</div>

<% end %>

app/views/sales_leadx/sales_leads/update.html.erb
<h4>SalesLeads#update</h4>
<p>Find me in app/views/customerx/sales_leads/update.html.erb</p>